// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backoffice/internal/adapter/broker"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewBrokerMock creates a new instance of BrokerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrokerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrokerMock {
	mock := &BrokerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BrokerMock is an autogenerated mock type for the Broker type
type BrokerMock struct {
	mock.Mock
}

type BrokerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *BrokerMock) EXPECT() *BrokerMock_Expecter {
	return &BrokerMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type BrokerMock
func (_mock *BrokerMock) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BrokerMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type BrokerMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *BrokerMock_Expecter) Close() *BrokerMock_Close_Call {
	return &BrokerMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *BrokerMock_Close_Call) Run(run func()) *BrokerMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *BrokerMock_Close_Call) Return(err error) *BrokerMock_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrokerMock_Close_Call) RunAndReturn(run func() error) *BrokerMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consumer provides a mock function for the type BrokerMock
func (_mock *BrokerMock) Consumer(ctx context.Context) (<-chan broker.Delivery, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Consumer")
	}

	var r0 <-chan broker.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (<-chan broker.Delivery, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan broker.Delivery); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan broker.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BrokerMock_Consumer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consumer'
type BrokerMock_Consumer_Call struct {
	*mock.Call
}

// Consumer is a helper method to define mock.On call
//   - ctx context.Context
func (_e *BrokerMock_Expecter) Consumer(ctx interface{}) *BrokerMock_Consumer_Call {
	return &BrokerMock_Consumer_Call{Call: _e.mock.On("Consumer", ctx)}
}

func (_c *BrokerMock_Consumer_Call) Run(run func(ctx context.Context)) *BrokerMock_Consumer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *BrokerMock_Consumer_Call) Return(deliveryCh <-chan broker.Delivery, err error) *BrokerMock_Consumer_Call {
	_c.Call.Return(deliveryCh, err)
	return _c
}

func (_c *BrokerMock_Consumer_Call) RunAndReturn(run func(ctx context.Context) (<-chan broker.Delivery, error)) *BrokerMock_Consumer_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type BrokerMock
func (_mock *BrokerMock) Publish(ctx context.Context, payload []byte) error {
	ret := _mock.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = returnFunc(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// BrokerMock_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type BrokerMock_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - payload []byte
func (_e *BrokerMock_Expecter) Publish(ctx interface{}, payload interface{}) *BrokerMock_Publish_Call {
	return &BrokerMock_Publish_Call{Call: _e.mock.On("Publish", ctx, payload)}
}

func (_c *BrokerMock_Publish_Call) Run(run func(ctx context.Context, payload []byte)) *BrokerMock_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *BrokerMock_Publish_Call) Return(err error) *BrokerMock_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *BrokerMock_Publish_Call) RunAndReturn(run func(ctx context.Context, payload []byte) error) *BrokerMock_Publish_Call {
	_c.Call.Return(run)
	return _c
}
