// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backoffice/internal/domain/task_in/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTaskInProcessUseCaseMock creates a new instance of TaskInProcessUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskInProcessUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskInProcessUseCaseMock {
	mock := &TaskInProcessUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskInProcessUseCaseMock is an autogenerated mock type for the UseCase type
type TaskInProcessUseCaseMock struct {
	mock.Mock
}

type TaskInProcessUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskInProcessUseCaseMock) EXPECT() *TaskInProcessUseCaseMock_Expecter {
	return &TaskInProcessUseCaseMock_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type TaskInProcessUseCaseMock
func (_mock *TaskInProcessUseCaseMock) Process(ctx context.Context, ct *dto.Task) error {
	ret := _mock.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Task) error); ok {
		r0 = returnFunc(ctx, ct)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskInProcessUseCaseMock_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type TaskInProcessUseCaseMock_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - ct *dto.Task
func (_e *TaskInProcessUseCaseMock_Expecter) Process(ctx interface{}, ct interface{}) *TaskInProcessUseCaseMock_Process_Call {
	return &TaskInProcessUseCaseMock_Process_Call{Call: _e.mock.On("Process", ctx, ct)}
}

func (_c *TaskInProcessUseCaseMock_Process_Call) Run(run func(ctx context.Context, ct *dto.Task)) *TaskInProcessUseCaseMock_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Task
		if args[1] != nil {
			arg1 = args[1].(*dto.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskInProcessUseCaseMock_Process_Call) Return(err error) *TaskInProcessUseCaseMock_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskInProcessUseCaseMock_Process_Call) RunAndReturn(run func(ctx context.Context, ct *dto.Task) error) *TaskInProcessUseCaseMock_Process_Call {
	_c.Call.Return(run)
	return _c
}
