// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"backoffice/internal/domain/task_out/dto"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTaskOutProcessUseCaseMock creates a new instance of TaskOutProcessUseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskOutProcessUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskOutProcessUseCaseMock {
	mock := &TaskOutProcessUseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskOutProcessUseCaseMock is an autogenerated mock type for the UseCase type
type TaskOutProcessUseCaseMock struct {
	mock.Mock
}

type TaskOutProcessUseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskOutProcessUseCaseMock) EXPECT() *TaskOutProcessUseCaseMock_Expecter {
	return &TaskOutProcessUseCaseMock_Expecter{mock: &_m.Mock}
}

// Process provides a mock function for the type TaskOutProcessUseCaseMock
func (_mock *TaskOutProcessUseCaseMock) Process(ctx context.Context, ct *dto.TaskOut) error {
	ret := _mock.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.TaskOut) error); ok {
		r0 = returnFunc(ctx, ct)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskOutProcessUseCaseMock_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type TaskOutProcessUseCaseMock_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - ct *dto.TaskOut
func (_e *TaskOutProcessUseCaseMock_Expecter) Process(ctx interface{}, ct interface{}) *TaskOutProcessUseCaseMock_Process_Call {
	return &TaskOutProcessUseCaseMock_Process_Call{Call: _e.mock.On("Process", ctx, ct)}
}

func (_c *TaskOutProcessUseCaseMock_Process_Call) Run(run func(ctx context.Context, ct *dto.TaskOut)) *TaskOutProcessUseCaseMock_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.TaskOut
		if args[1] != nil {
			arg1 = args[1].(*dto.TaskOut)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskOutProcessUseCaseMock_Process_Call) Return(err error) *TaskOutProcessUseCaseMock_Process_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskOutProcessUseCaseMock_Process_Call) RunAndReturn(run func(ctx context.Context, ct *dto.TaskOut) error) *TaskOutProcessUseCaseMock_Process_Call {
	_c.Call.Return(run)
	return _c
}
